package edneyosf.edconv.ffmpeg.ffmpeg

object FFmpegArgs {
    const val LOG_LEVEL = "-loglevel"
    const val INPUT = "-i"
    const val OVERRIDE_INPUT = "-r"
    const val FORCE = "-f"
    const val MAP = "-map"
    const val ENCODER_AUDIO = "-c:a"
    const val ENCODER_VIDEO = "-c:v"
    const val ENCODER_SUBTITLES = "-c:s"
    const val BITRATE_AUDIO = "-b:a"
    const val BITRATE_VIDEO = "-b:v"
    const val VBR = "-vbr"
    const val SAMPLE_RATE = "-ar"
    const val CHANNELS = "-ac"
    const val PRESET = "-preset"
    const val CRF = "-crf"
    const val PROFILE_VIDEO = "-profile:v"
    const val PROFILE_AUDIO = "-profile:a"
    const val PIXEL_FORMAT = "-pix_fmt"
    const val NO_AUDIO = "-an"
    const val NO_SUBTITLE = "-sn"
    const val FILTER_AUDIO = "-af"
    const val FILTER_VIDEO = "-vf"
    const val MAPPING_FAMILY = "-mapping_family"
    const val COPY = "copy"
    const val MAP_METADATA = "-map_metadata"
    const val MAP_CHAPTERS = "-map_chapters"
    const val FILTER_AV = "-lavfi"
    const val STATS = "-stats"
}