package edneyosf.edconv.core.common

enum class Error(val code: String) {
    DEFAULT(code = "0000"),
    LOAD_CONFIGS(code = "0001"),
    UNKNOWN_INPUT_MEDIA(code = "0002"),
    NO_DURATION_INPUT_MEDIA(code = "0003"),
    NO_CHANNELS_INPUT_MEDIA(code = "0004"),
    NO_RESOLUTION_INPUT_MEDIA(code = "0005"),
    NO_STREAM_FOUND_INPUT_MEDIA(code = "0006"),
    FFMPEG_OR_FFPROBE_VERIFICATION(code = "0007"),
    CONFIGURATION_SAVE(code = "0008"),
    ON_ADD_TO_QUEUE(code = "0009"),
    ON_ADD_TO_QUEUE_REQUIREMENTS(code = "000A"),
    ON_STOPPING_CONVERSION(code = "000B"),
    START_TIME_NULL(code = "000C"),
    INPUT_FILE_NOT_EXIST(code = "000D"),
    INPUT_NOT_FILE(code = "000E"),
    CONVERSION_PROCESS_COMPLETED(code = "000F"),
    PROCESS_NULL(code = "000G"),
    CONVERSION_PROCESS(code = "000H"),
    METRICS_PROCESS_COMPLETED(code = "000I"),
    METRICS_PROCESS(code = "000J"),
    METRICS_SCORE_NULL(code = "000K"),
    ON_STOPPING_METRICS(code = "000L"),
    ON_STARTING_METRICS_REQUIREMENTS(code = "000M"),
    NO_VIDEO_INPUT_MEDIA(code = "000N"),
    METRICS_MODEL_SAVE(code = "000O"),
    FILE_ALREADY_EXISTS(code = "000P")
}