name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: [x86_64, arm64]
          - runner: macos-latest
            arch: [x86_64, arm64]
          - runner: windows-latest
            arch: [ x86_64, arm64 ]

    runs-on: ${{ matrix.runner }}

    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Check with Gradle Wrapper
        run: ./gradlew check