name: Linux Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm64

    runs-on: ${{ matrix.runner }}

    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder   

      - name: Install Flatpak SDK and extensions
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//25.08
          sudo flatpak install -y flathub org.freedesktop.Sdk//25.08
          sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.openjdk21//25.08

      - name: Install libfuse2
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Create .flatpak release
        run: ./scripts/createFlatpakRelease.sh

      - name: Create .AppImage release
        run: ./scripts/createAppImageRelease.sh

      - name: Create .deb release
        run: ./scripts/createDebRelease.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-${{ matrix.arch }}
          path: |
            *.deb
            *.flatpak
            *.AppImage