name: Linux Build

on:
  push:
    tags: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew packageDeb

    - name: Locate .deb file
      id: find_deb
      run: |
        FILE=$(find build/compose/binaries/main/deb -type f -name "*.deb" | head -n 1)
        echo "deb_path=$FILE" >> $GITHUB_OUTPUT

    - name: Upload .deb to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_deb.outputs.deb_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
