name: Linux Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder   

      - name: Install Flatpak SDK and extensions
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform/x86_64/25.08
          sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.openjdk17//25.08    
          
      - name: Install AppImage tools
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Download appimagetool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage    

      - name: Create .flatpak release
        run: ./scripts/createFlatpakRelease.sh

      - name: Create .AppImage release
        run: ./scripts/createAppImageRelease.sh

      - name: Create .deb release
        run: ./gradlew createDeb --no-build-cache

      - name: Create .rpm release
        run: ./gradlew packageReleaseRpm --no-build-cache

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: |
            composeApp/build/compose/binaries/main-release/deb/*.deb
            composeApp/build/compose/binaries/main-release/rpm/*.rpm
            *.flatpak
            *.AppImage
