name: Linux Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build .deb with Gradle
      run: ./gradlew createDeb

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-release
        path: composeApp/build/compose/binaries/main/deb/*.deb
