name: macOS Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: macos-13
            arch: x86_64
          - runner: macos-latest
            arch: arm64

    runs-on: ${{ matrix.runner }}

    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Create MacOS release
        run: ./scripts/createMacRelease.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release-${{ matrix.arch }}
          path: |
            composeApp/build/compose/binaries/main-release/dmg/*.dmg