name: MacOS Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create MacOS release
        run: ./scripts/createMacRelease.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: |
            composeApp/build/compose/binaries/main-release/dmg/*.dmg