name: Windows Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Windows release
        run: ./scripts/createWindowsRelease.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            composeApp\build\compose\binaries\main-release\exe\*.exe