name: Windows Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build .exe with Gradle
      run: ./gradlew packageReleaseExe --no-build-cache

    - name: Build .msi with Gradle
      run: ./gradlew packageReleaseMsi --no-build-cache

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: |
          composeApp\build\compose\binaries\main-release\msi\*.msi
          composeApp\build\compose\binaries\main-release\exe\*.exe
