name: Windows Build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            arch: x86_64
          - runner: windows-11-arm
            arch: arm64

    runs-on: ${{ matrix.runner }}

    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Create Windows release
        run: ./scripts/createWindowsRelease.sh
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-${{ matrix.arch }}
          path: |
            composeApp\build\compose\binaries\main-release\exe\*.exe