name: Windows Build

on:
  push:
    tags:
      - 'v*'

jobs:

  linux-build:
    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew packageExe

    - name: Find .exe file
      id: find_file
      shell: pwsh
      run: |
        $exe = Get-ChildItem -Path "build\compose\binaries\main\exe" -Filter *.exe | Select-Object -First 1
        echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT
        Write-Host "Found: $($exe.FullName)"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.find_file.outputs.exe_path }}
        if-no-files-found: error